### ISSUE TITLE
Invite Fireflies to all meetings

### ISSUE THREAD

**Issue by varunvraja** [VilllageBookBuilders/VBBPortal#112]
Invite fred@fireflies.ai to a calendar invites from the python script

**Comment by edringger** [comment]
Varun has signed us up for a fireflies.io automatic transcription service. this will allow us to better track and understand what is going on in mentoring sessions

**Comment by edringger** [comment]
Issue moved to [VilllageBookBuilders/backend-vbb-portal #3](https://github.com/VilllageBookBuilders/backend-vbb-portal/issues/3) via [**ZenHub**](https://www.zenhub.com/)
