### ISSUE TITLE
change google sign in from popup to be a sidetab sign in

### ISSUE THREAD

**Issue by varunvraja** [VilllageBookBuilders/VBBPortal#115]
people are having difficulty with the popup button to login into the village portal. Can we change it so a new tab with google sign-in is shown instead of a windows pop-up? ask Varun for clarification

**Comment by NirajNair** [comment]
Can I take up this issue?

**Comment by varunvraja** [comment]
@NirajNair Yeah sure thx, let me know if you need more information on this issue!

**Comment by KeerthanaaN** [comment]
@NirajNair Hey Niraj! Could you mail us at support@villagebookbuilders.org  to further discuss about the issue ?
