### ISSUE TITLE
Name change of VBB Portal Name to Village Portal

### ISSUE THREAD

**Issue by varunvraja** [VilllageBookBuilders/VBBPortal#116]
Hi everyone, for who takes this task, please change all wording from vbb portal to village portal (most of the org prefers village portal > vbb portal). Ctrl find in the repos and change all strings, text, repo names, readme to village portal. 
Priority: Low
Complexity: Low

**Comment by varunvraja** [comment]
done? @edringger can you make sure when you have time?

**Comment by edringger** [comment]
we had an extensive discussion on this over the summer. why do we want to change it back?
