### ISSUE TITLE
JWT life is short for the staging server

### ISSUE THREAD

**Issue by ferror18** [VilllageBookBuilders/VBBPortal#120]
If posible, would be good to set the life of JTW's to 24 h or 48h only in the staging server. To allow to develop more easily

**Comment by ferror18** [comment]
The lambda team is currently not using our own deployed server; instead, they're using a clone of our server with some basic authentication set up using JWT's. Since this authentication is just a placeholder for the google authentication when we finally get it polished and fully tested, it would be good to make two changes to the basic auth that the clone back-end currently has.

First, change the life of the JWT to a long period, say 24 or 48 hours, so that they don't have to keep signing in to the system. Also, changing the token type from Bearer to a simple 'Authorization' a second change mainly because lambda is more familiar with this type of token.

**Comment by nivedasai** [comment]
Moving this to new Refactored BE ,as a part of organizing Zenhub
