### ISSUE TITLE
Seeding Script

### ISSUE THREAD

**Issue by ferror18** [VilllageBookBuilders/VBBPortal#123]
While we prepare the new back-end to be available to lambdas development teams, some of their concerns are that they're not familiar with python back-ends. Our current back-end consists of Django, and the way we can create dummy data without a full fledged API is trough the Django admin portal; this is fine if we are testing for small amounts of users, but it can become tedious to create a large number of users, programs, libraries, etc.

With the help of Vignesh, I started creating a seeding script as part of the python management commands, and the idea is that this script will create users and their needed objects (program, library, school). In the end, it will also remove all the fake data from the database if needed. So the seeding can occur without leaving any trace in the database.

**Comment by nivedasai** [comment]
Moving this to new Refactored BE ,as a part of organizing Zenhub
