### ISSUE TITLE
Update Readme document with all the instructions Vignesh showed Manuel and Varun

### ISSUE THREAD

**Issue by varunvraja** [VilllageBookBuilders/VBBPortal#124]
add the ubuntu and windows versions 
for setting up the project
for setting up Postgres database
for setting up APIs to be displayed on swagger
for setting up er diagram generation

and wording of how an accepted PR to master will automatically update on Heroku. 

@vigneshhari will do the ubuntu version & @varunvraja will update with window version commands

**Comment by nivedasai** [comment]
Moving this to new Refactored BE ,as a part of organizing Zenhub
