### ISSUE TITLE
Adjustments to the session details page

### ISSUE THREAD

**Issue by ximena9201** [VilllageBookBuilders/VBBPortal#125]
1. Remove end dates from all mentoring sessions. 
2. Make the unbooking button available ONLY if the current user is the mentor advisor. This will probably involve making a very basic mentor advisor logon
3. Add a note with suggestions on how to use the "session notes" text box
4. Add the hangouts link to the session details page

**Comment by varunvraja** [comment]
@ximena9201 this is complete right? if so can you close the issue or let's meet sometime to work on it?

**Comment by ximena9201** [comment]
@varunvraja  @nivedasai I'm gonna close it. Since we have a new repo and we're moving everything to it so these adjustments will be worked on the new repo
