### ISSUE TITLE
Mail Chimp

### ISSUE THREAD

**Issue by varunvraja** [VilllageBookBuilders/VBBPortal#24]
Issue: Mail Chimp
Id:1188742709629114
Due Date: 2020-08-29
Assignee:Shwetha Shinju

**Comment by edringger** [comment]
simply subscribe user to our mailchimp newsletter after they click "next" on the first step of the registration page

**Comment by Aleksei-Zaichenko** [comment]
Mme and Sarthak completed this issue. We modified both front-end and back-end to solve the issue. While solving the issue, we added a new rest api endpoint.
