### ISSUE TITLE
On the home page change the text for Validate.... to just "Sign in"
Change sign in button to say "PORTAL" or portal homepage, or add button to dashboard or something? and seperate sign in button?

### ISSUE THREAD

**Issue by varunvraja** [VilllageBookBuilders/VBBPortal#37]
Issue: On the home page change the text for Validate.... to just "Sign in"
Change sign in button to say "PORTAL" or portal homepage, or add button to dashboard or something? and seperate sign in button?
Id:1192213716551539
Due Date: 
Assignee:Brigham Andersen

**Comment by edringger** [comment]
completed
