### ISSUE TITLE
Move the donation section to the very end under the notification for them to check their email, and have it redirect them to an external WP FORM copying the text and style as shown in the old registration process so we can do recurring donations, This will be temporary until we can figure out how to incorporate recurring payments with Stripe in the portal

### ISSUE THREAD

**Issue by varunvraja** [VilllageBookBuilders/VBBPortal#40]
Issue: Move the donation section to the very end under the notification for them to check their email, and have it redirect them to an external WP FORM copying the text and style as shown in the old registration process so we can do recurring donations, This will be temporary until we can figure out how to incorporate recurring payments with Stripe in the portal
Id:1192213716551546
Due Date: 
Assignee:Varun Raja

**Comment by edringger** [comment]
completed
