### ISSUE TITLE
in the registration process when it asks what organization they are involved in saying this instead "What corporation, organization, or Village Mentors Club are you affiliated with?   Change the suggestion text to ie 'Nike' - if none leave blank



### ISSUE THREAD

**Issue by varunvraja** [VilllageBookBuilders/VBBPortal#41]
Issue: in the registration process when it asks what organization they are involved in saying this instead "What corporation, organization, or Village Mentors Club are you affiliated with?   Change the suggestion text to ie 'Nike' - if none leave blank

Id:1192213716551548
Due Date: 
Assignee:Ed Ringger

**Comment by qwestionmark** [comment]
@varunvraja it looks like this fix has been pushed to master. If so, can we close this ticket?

**Comment by edringger** [comment]
completed
