### ISSUE TITLE
add 7 day + notice to booking tool (note will use mobi calender later on ) - need django - longer booking process for 1.5... figure it out get a booking tool analyze the code for asynchonuse appointment

### ISSUE THREAD

**Issue by KeerthanaaN** [VilllageBookBuilders/VBBPortal#74]

**Comment by edringger** [comment]
@varunvraja can you elaborate on this one as well?

**Comment by edringger** [comment]
closed for now. we will redesign the booking tool and possibly only onboard new mentors on the first of each month to streamline the process

**Comment by varunvraja** [comment]
https://demo.mobiscroll.com/datetime/mobile-desktop-usage
