### ISSUE TITLE
Set up database backups

### ISSUE THREAD

**Issue by KeerthanaaN** [VilllageBookBuilders/VBBPortal#84]

**Comment by qwestionmark** [comment]
@KeerthanaaN this should be a top-priority. If a database is accidentally erased or corrupted it could break the app for any number of users and cause unrecoverable errors.

**Comment by KeerthanaaN** [comment]
@qwestionmark  Thanks for bring that up Trevor! @BishtSarthak  Are we currently on this Sarthak/ can we commit to this at the earliest?

**Comment by BishtSarthak** [comment]
Incremental backups are being managed (automatically) by Oracle ATP. Will replicate the entire database when creating separate staging and production servers. Closing this issue for now.
